#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLHH")]
public partial class QLHangHoaDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertCHITIETDATHANG(CHITIETDATHANG instance);
  partial void UpdateCHITIETDATHANG(CHITIETDATHANG instance);
  partial void DeleteCHITIETDATHANG(CHITIETDATHANG instance);
  partial void InsertDONDATHANG(DONDATHANG instance);
  partial void UpdateDONDATHANG(DONDATHANG instance);
  partial void DeleteDONDATHANG(DONDATHANG instance);
  partial void InsertKHACHHANG(KHACHHANG instance);
  partial void UpdateKHACHHANG(KHACHHANG instance);
  partial void DeleteKHACHHANG(KHACHHANG instance);
  partial void InsertLOAIHANG(LOAIHANG instance);
  partial void UpdateLOAIHANG(LOAIHANG instance);
  partial void DeleteLOAIHANG(LOAIHANG instance);
  partial void InsertNHACUNGCAP(NHACUNGCAP instance);
  partial void UpdateNHACUNGCAP(NHACUNGCAP instance);
  partial void DeleteNHACUNGCAP(NHACUNGCAP instance);
  partial void InsertNHANVIEN(NHANVIEN instance);
  partial void UpdateNHANVIEN(NHANVIEN instance);
  partial void DeleteNHANVIEN(NHANVIEN instance);
  partial void InsertSANPHAM(SANPHAM instance);
  partial void UpdateSANPHAM(SANPHAM instance);
  partial void DeleteSANPHAM(SANPHAM instance);
  #endregion
	
	public QLHangHoaDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLHHConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public QLHangHoaDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QLHangHoaDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QLHangHoaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QLHangHoaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<CHITIETDATHANG> CHITIETDATHANGs
	{
		get
		{
			return this.GetTable<CHITIETDATHANG>();
		}
	}
	
	public System.Data.Linq.Table<DONDATHANG> DONDATHANGs
	{
		get
		{
			return this.GetTable<DONDATHANG>();
		}
	}
	
	public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
	{
		get
		{
			return this.GetTable<KHACHHANG>();
		}
	}
	
	public System.Data.Linq.Table<LOAIHANG> LOAIHANGs
	{
		get
		{
			return this.GetTable<LOAIHANG>();
		}
	}
	
	public System.Data.Linq.Table<NHACUNGCAP> NHACUNGCAPs
	{
		get
		{
			return this.GetTable<NHACUNGCAP>();
		}
	}
	
	public System.Data.Linq.Table<NHANVIEN> NHANVIENs
	{
		get
		{
			return this.GetTable<NHANVIEN>();
		}
	}
	
	public System.Data.Linq.Table<SANPHAM> SANPHAMs
	{
		get
		{
			return this.GetTable<SANPHAM>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDATHANG")]
public partial class CHITIETDATHANG : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _SoDDH;
	
	private string _MaSP;
	
	private System.Nullable<long> _GiaBan;
	
	private System.Nullable<int> _SoLuong;
	
	private System.Nullable<int> _MucGiamGia;
	
	private EntityRef<DONDATHANG> _DONDATHANG;
	
	private EntityRef<SANPHAM> _SANPHAM;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoDDHChanging(string value);
    partial void OnSoDDHChanged();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnGiaBanChanging(System.Nullable<long> value);
    partial void OnGiaBanChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnMucGiamGiaChanging(System.Nullable<int> value);
    partial void OnMucGiamGiaChanged();
    #endregion
	
	public CHITIETDATHANG()
	{
		this._DONDATHANG = default(EntityRef<DONDATHANG>);
		this._SANPHAM = default(EntityRef<SANPHAM>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDDH", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SoDDH
	{
		get
		{
			return this._SoDDH;
		}
		set
		{
			if ((this._SoDDH != value))
			{
				if (this._DONDATHANG.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnSoDDHChanging(value);
				this.SendPropertyChanging();
				this._SoDDH = value;
				this.SendPropertyChanged("SoDDH");
				this.OnSoDDHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaSP
	{
		get
		{
			return this._MaSP;
		}
		set
		{
			if ((this._MaSP != value))
			{
				if (this._SANPHAM.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaSPChanging(value);
				this.SendPropertyChanging();
				this._MaSP = value;
				this.SendPropertyChanged("MaSP");
				this.OnMaSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="BigInt")]
	public System.Nullable<long> GiaBan
	{
		get
		{
			return this._GiaBan;
		}
		set
		{
			if ((this._GiaBan != value))
			{
				this.OnGiaBanChanging(value);
				this.SendPropertyChanging();
				this._GiaBan = value;
				this.SendPropertyChanged("GiaBan");
				this.OnGiaBanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
	public System.Nullable<int> SoLuong
	{
		get
		{
			return this._SoLuong;
		}
		set
		{
			if ((this._SoLuong != value))
			{
				this.OnSoLuongChanging(value);
				this.SendPropertyChanging();
				this._SoLuong = value;
				this.SendPropertyChanged("SoLuong");
				this.OnSoLuongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucGiamGia", DbType="Int")]
	public System.Nullable<int> MucGiamGia
	{
		get
		{
			return this._MucGiamGia;
		}
		set
		{
			if ((this._MucGiamGia != value))
			{
				this.OnMucGiamGiaChanging(value);
				this.SendPropertyChanging();
				this._MucGiamGia = value;
				this.SendPropertyChanged("MucGiamGia");
				this.OnMucGiamGiaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONDATHANG_CHITIETDATHANG", Storage="_DONDATHANG", ThisKey="SoDDH", OtherKey="SoDDH", IsForeignKey=true)]
	internal DONDATHANG DONDATHANG
	{
		get
		{
			return this._DONDATHANG.Entity;
		}
		set
		{
			DONDATHANG previousValue = this._DONDATHANG.Entity;
			if (((previousValue != value) 
						|| (this._DONDATHANG.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._DONDATHANG.Entity = null;
					previousValue.CHITIETDATHANGs.Remove(this);
				}
				this._DONDATHANG.Entity = value;
				if ((value != null))
				{
					value.CHITIETDATHANGs.Add(this);
					this._SoDDH = value.SoDDH;
				}
				else
				{
					this._SoDDH = default(string);
				}
				this.SendPropertyChanged("DONDATHANG");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CHITIETDATHANG", Storage="_SANPHAM", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
	internal SANPHAM SANPHAM
	{
		get
		{
			return this._SANPHAM.Entity;
		}
		set
		{
			SANPHAM previousValue = this._SANPHAM.Entity;
			if (((previousValue != value) 
						|| (this._SANPHAM.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._SANPHAM.Entity = null;
					previousValue.CHITIETDATHANGs.Remove(this);
				}
				this._SANPHAM.Entity = value;
				if ((value != null))
				{
					value.CHITIETDATHANGs.Add(this);
					this._MaSP = value.MaSP;
				}
				else
				{
					this._MaSP = default(string);
				}
				this.SendPropertyChanged("SANPHAM");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONDATHANG")]
public partial class DONDATHANG : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _SoDDH;
	
	private string _MaKH;
	
	private string _MaNV;
	
	private System.Nullable<System.DateTime> _NgayDat;
	
	private EntitySet<CHITIETDATHANG> _CHITIETDATHANGs;
	
	private EntityRef<KHACHHANG> _KHACHHANG;
	
	private EntityRef<NHANVIEN> _NHANVIEN;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoDDHChanging(string value);
    partial void OnSoDDHChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    #endregion
	
	public DONDATHANG()
	{
		this._CHITIETDATHANGs = new EntitySet<CHITIETDATHANG>(new Action<CHITIETDATHANG>(this.attach_CHITIETDATHANGs), new Action<CHITIETDATHANG>(this.detach_CHITIETDATHANGs));
		this._KHACHHANG = default(EntityRef<KHACHHANG>);
		this._NHANVIEN = default(EntityRef<NHANVIEN>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDDH", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string SoDDH
	{
		get
		{
			return this._SoDDH;
		}
		set
		{
			if ((this._SoDDH != value))
			{
				this.OnSoDDHChanging(value);
				this.SendPropertyChanging();
				this._SoDDH = value;
				this.SendPropertyChanged("SoDDH");
				this.OnSoDDHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(50)")]
	public string MaKH
	{
		get
		{
			return this._MaKH;
		}
		set
		{
			if ((this._MaKH != value))
			{
				if (this._KHACHHANG.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaKHChanging(value);
				this.SendPropertyChanging();
				this._MaKH = value;
				this.SendPropertyChanged("MaKH");
				this.OnMaKHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(50)")]
	public string MaNV
	{
		get
		{
			return this._MaNV;
		}
		set
		{
			if ((this._MaNV != value))
			{
				if (this._NHANVIEN.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaNVChanging(value);
				this.SendPropertyChanging();
				this._MaNV = value;
				this.SendPropertyChanged("MaNV");
				this.OnMaNVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgayDat
	{
		get
		{
			return this._NgayDat;
		}
		set
		{
			if ((this._NgayDat != value))
			{
				this.OnNgayDatChanging(value);
				this.SendPropertyChanging();
				this._NgayDat = value;
				this.SendPropertyChanged("NgayDat");
				this.OnNgayDatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONDATHANG_CHITIETDATHANG", Storage="_CHITIETDATHANGs", ThisKey="SoDDH", OtherKey="SoDDH")]
	public EntitySet<CHITIETDATHANG> CHITIETDATHANGs
	{
		get
		{
			return this._CHITIETDATHANGs;
		}
		set
		{
			this._CHITIETDATHANGs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DONDATHANG", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
	internal KHACHHANG KHACHHANG
	{
		get
		{
			return this._KHACHHANG.Entity;
		}
		set
		{
			KHACHHANG previousValue = this._KHACHHANG.Entity;
			if (((previousValue != value) 
						|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._KHACHHANG.Entity = null;
					previousValue.DONDATHANGs.Remove(this);
				}
				this._KHACHHANG.Entity = value;
				if ((value != null))
				{
					value.DONDATHANGs.Add(this);
					this._MaKH = value.MaKH;
				}
				else
				{
					this._MaKH = default(string);
				}
				this.SendPropertyChanged("KHACHHANG");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_DONDATHANG", Storage="_NHANVIEN", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
	internal NHANVIEN NHANVIEN
	{
		get
		{
			return this._NHANVIEN.Entity;
		}
		set
		{
			NHANVIEN previousValue = this._NHANVIEN.Entity;
			if (((previousValue != value) 
						|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._NHANVIEN.Entity = null;
					previousValue.DONDATHANGs.Remove(this);
				}
				this._NHANVIEN.Entity = value;
				if ((value != null))
				{
					value.DONDATHANGs.Add(this);
					this._MaNV = value.MaNV;
				}
				else
				{
					this._MaNV = default(string);
				}
				this.SendPropertyChanged("NHANVIEN");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_CHITIETDATHANGs(CHITIETDATHANG entity)
	{
		this.SendPropertyChanging();
		entity.DONDATHANG = this;
	}
	
	private void detach_CHITIETDATHANGs(CHITIETDATHANG entity)
	{
		this.SendPropertyChanging();
		entity.DONDATHANG = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaKH;
	
	private string _Ho;
	
	private string _Ten;
	
	private string _DiaChi;
	
	private string _Email;
	
	private string _DienThoai;
	
	private EntitySet<DONDATHANG> _DONDATHANGs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnHoChanging(string value);
    partial void OnHoChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    #endregion
	
	public KHACHHANG()
	{
		this._DONDATHANGs = new EntitySet<DONDATHANG>(new Action<DONDATHANG>(this.attach_DONDATHANGs), new Action<DONDATHANG>(this.detach_DONDATHANGs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaKH
	{
		get
		{
			return this._MaKH;
		}
		set
		{
			if ((this._MaKH != value))
			{
				this.OnMaKHChanging(value);
				this.SendPropertyChanging();
				this._MaKH = value;
				this.SendPropertyChanged("MaKH");
				this.OnMaKHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho", DbType="NVarChar(MAX)")]
	public string Ho
	{
		get
		{
			return this._Ho;
		}
		set
		{
			if ((this._Ho != value))
			{
				this.OnHoChanging(value);
				this.SendPropertyChanging();
				this._Ho = value;
				this.SendPropertyChanged("Ho");
				this.OnHoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(MAX)")]
	public string Ten
	{
		get
		{
			return this._Ten;
		}
		set
		{
			if ((this._Ten != value))
			{
				this.OnTenChanging(value);
				this.SendPropertyChanging();
				this._Ten = value;
				this.SendPropertyChanged("Ten");
				this.OnTenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(50)")]
	public string DienThoai
	{
		get
		{
			return this._DienThoai;
		}
		set
		{
			if ((this._DienThoai != value))
			{
				this.OnDienThoaiChanging(value);
				this.SendPropertyChanging();
				this._DienThoai = value;
				this.SendPropertyChanged("DienThoai");
				this.OnDienThoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DONDATHANG", Storage="_DONDATHANGs", ThisKey="MaKH", OtherKey="MaKH")]
	public EntitySet<DONDATHANG> DONDATHANGs
	{
		get
		{
			return this._DONDATHANGs;
		}
		set
		{
			this._DONDATHANGs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_DONDATHANGs(DONDATHANG entity)
	{
		this.SendPropertyChanging();
		entity.KHACHHANG = this;
	}
	
	private void detach_DONDATHANGs(DONDATHANG entity)
	{
		this.SendPropertyChanging();
		entity.KHACHHANG = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIHANG")]
public partial class LOAIHANG : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaLoai;
	
	private string _TenLoai;
	
	private EntitySet<SANPHAM> _SANPHAMs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
	
	public LOAIHANG()
	{
		this._SANPHAMs = new EntitySet<SANPHAM>(new Action<SANPHAM>(this.attach_SANPHAMs), new Action<SANPHAM>(this.detach_SANPHAMs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaLoai
	{
		get
		{
			return this._MaLoai;
		}
		set
		{
			if ((this._MaLoai != value))
			{
				this.OnMaLoaiChanging(value);
				this.SendPropertyChanging();
				this._MaLoai = value;
				this.SendPropertyChanged("MaLoai");
				this.OnMaLoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(MAX)")]
	public string TenLoai
	{
		get
		{
			return this._TenLoai;
		}
		set
		{
			if ((this._TenLoai != value))
			{
				this.OnTenLoaiChanging(value);
				this.SendPropertyChanging();
				this._TenLoai = value;
				this.SendPropertyChanged("TenLoai");
				this.OnTenLoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHANG_SANPHAM", Storage="_SANPHAMs", ThisKey="MaLoai", OtherKey="MaLH")]
	public EntitySet<SANPHAM> SANPHAMs
	{
		get
		{
			return this._SANPHAMs;
		}
		set
		{
			this._SANPHAMs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_SANPHAMs(SANPHAM entity)
	{
		this.SendPropertyChanging();
		entity.LOAIHANG = this;
	}
	
	private void detach_SANPHAMs(SANPHAM entity)
	{
		this.SendPropertyChanging();
		entity.LOAIHANG = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHACUNGCAP")]
public partial class NHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaNCC;
	
	private string _TenNCC;
	
	private string _DiaChi;
	
	private string _DienThoai;
	
	private string _Email;
	
	private EntitySet<SANPHAM> _SANPHAMs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
	
	public NHACUNGCAP()
	{
		this._SANPHAMs = new EntitySet<SANPHAM>(new Action<SANPHAM>(this.attach_SANPHAMs), new Action<SANPHAM>(this.detach_SANPHAMs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaNCC
	{
		get
		{
			return this._MaNCC;
		}
		set
		{
			if ((this._MaNCC != value))
			{
				this.OnMaNCCChanging(value);
				this.SendPropertyChanging();
				this._MaNCC = value;
				this.SendPropertyChanged("MaNCC");
				this.OnMaNCCChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(MAX)")]
	public string TenNCC
	{
		get
		{
			return this._TenNCC;
		}
		set
		{
			if ((this._TenNCC != value))
			{
				this.OnTenNCCChanging(value);
				this.SendPropertyChanging();
				this._TenNCC = value;
				this.SendPropertyChanged("TenNCC");
				this.OnTenNCCChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(11)")]
	public string DienThoai
	{
		get
		{
			return this._DienThoai;
		}
		set
		{
			if ((this._DienThoai != value))
			{
				this.OnDienThoaiChanging(value);
				this.SendPropertyChanging();
				this._DienThoai = value;
				this.SendPropertyChanged("DienThoai");
				this.OnDienThoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_SANPHAM", Storage="_SANPHAMs", ThisKey="MaNCC", OtherKey="MaNCC")]
	public EntitySet<SANPHAM> SANPHAMs
	{
		get
		{
			return this._SANPHAMs;
		}
		set
		{
			this._SANPHAMs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_SANPHAMs(SANPHAM entity)
	{
		this.SendPropertyChanging();
		entity.NHACUNGCAP = this;
	}
	
	private void detach_SANPHAMs(SANPHAM entity)
	{
		this.SendPropertyChanging();
		entity.NHACUNGCAP = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaNV;
	
	private string _Ho;
	
	private string _Ten;
	
	private string _GioiTinh;
	
	private System.Nullable<System.DateTime> _NgaySinh;
	
	private string _DiaChi;
	
	private string _DienThoai;
	
	private System.Nullable<double> _LuongCB;
	
	private System.Nullable<double> _PhuCap;
	
	private EntitySet<DONDATHANG> _DONDATHANGs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnHoChanging(string value);
    partial void OnHoChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnLuongCBChanging(System.Nullable<double> value);
    partial void OnLuongCBChanged();
    partial void OnPhuCapChanging(System.Nullable<double> value);
    partial void OnPhuCapChanged();
    #endregion
	
	public NHANVIEN()
	{
		this._DONDATHANGs = new EntitySet<DONDATHANG>(new Action<DONDATHANG>(this.attach_DONDATHANGs), new Action<DONDATHANG>(this.detach_DONDATHANGs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaNV
	{
		get
		{
			return this._MaNV;
		}
		set
		{
			if ((this._MaNV != value))
			{
				this.OnMaNVChanging(value);
				this.SendPropertyChanging();
				this._MaNV = value;
				this.SendPropertyChanged("MaNV");
				this.OnMaNVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho", DbType="NVarChar(MAX)")]
	public string Ho
	{
		get
		{
			return this._Ho;
		}
		set
		{
			if ((this._Ho != value))
			{
				this.OnHoChanging(value);
				this.SendPropertyChanging();
				this._Ho = value;
				this.SendPropertyChanged("Ho");
				this.OnHoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(MAX)")]
	public string Ten
	{
		get
		{
			return this._Ten;
		}
		set
		{
			if ((this._Ten != value))
			{
				this.OnTenChanging(value);
				this.SendPropertyChanging();
				this._Ten = value;
				this.SendPropertyChanged("Ten");
				this.OnTenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
	public string GioiTinh
	{
		get
		{
			return this._GioiTinh;
		}
		set
		{
			if ((this._GioiTinh != value))
			{
				this.OnGioiTinhChanging(value);
				this.SendPropertyChanging();
				this._GioiTinh = value;
				this.SendPropertyChanged("GioiTinh");
				this.OnGioiTinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgaySinh
	{
		get
		{
			return this._NgaySinh;
		}
		set
		{
			if ((this._NgaySinh != value))
			{
				this.OnNgaySinhChanging(value);
				this.SendPropertyChanging();
				this._NgaySinh = value;
				this.SendPropertyChanged("NgaySinh");
				this.OnNgaySinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(11)")]
	public string DienThoai
	{
		get
		{
			return this._DienThoai;
		}
		set
		{
			if ((this._DienThoai != value))
			{
				this.OnDienThoaiChanging(value);
				this.SendPropertyChanging();
				this._DienThoai = value;
				this.SendPropertyChanged("DienThoai");
				this.OnDienThoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongCB", DbType="Float")]
	public System.Nullable<double> LuongCB
	{
		get
		{
			return this._LuongCB;
		}
		set
		{
			if ((this._LuongCB != value))
			{
				this.OnLuongCBChanging(value);
				this.SendPropertyChanging();
				this._LuongCB = value;
				this.SendPropertyChanged("LuongCB");
				this.OnLuongCBChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuCap", DbType="Float")]
	public System.Nullable<double> PhuCap
	{
		get
		{
			return this._PhuCap;
		}
		set
		{
			if ((this._PhuCap != value))
			{
				this.OnPhuCapChanging(value);
				this.SendPropertyChanging();
				this._PhuCap = value;
				this.SendPropertyChanged("PhuCap");
				this.OnPhuCapChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_DONDATHANG", Storage="_DONDATHANGs", ThisKey="MaNV", OtherKey="MaNV")]
	public EntitySet<DONDATHANG> DONDATHANGs
	{
		get
		{
			return this._DONDATHANGs;
		}
		set
		{
			this._DONDATHANGs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_DONDATHANGs(DONDATHANG entity)
	{
		this.SendPropertyChanging();
		entity.NHANVIEN = this;
	}
	
	private void detach_DONDATHANGs(DONDATHANG entity)
	{
		this.SendPropertyChanging();
		entity.NHANVIEN = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SANPHAM")]
public partial class SANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaSP;
	
	private string _TenSP;
	
	private System.Nullable<int> _SoLuong;
	
	private string _DonViTinh;
	
	private System.Nullable<long> _DonGia;
	
	private string _MaNCC;
	
	private string _MaLH;
	
	private EntitySet<CHITIETDATHANG> _CHITIETDATHANGs;
	
	private EntityRef<LOAIHANG> _LOAIHANG;
	
	private EntityRef<NHACUNGCAP> _NHACUNGCAP;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    partial void OnDonGiaChanging(System.Nullable<long> value);
    partial void OnDonGiaChanged();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnMaLHChanging(string value);
    partial void OnMaLHChanged();
    #endregion
	
	public SANPHAM()
	{
		this._CHITIETDATHANGs = new EntitySet<CHITIETDATHANG>(new Action<CHITIETDATHANG>(this.attach_CHITIETDATHANGs), new Action<CHITIETDATHANG>(this.detach_CHITIETDATHANGs));
		this._LOAIHANG = default(EntityRef<LOAIHANG>);
		this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaSP
	{
		get
		{
			return this._MaSP;
		}
		set
		{
			if ((this._MaSP != value))
			{
				this.OnMaSPChanging(value);
				this.SendPropertyChanging();
				this._MaSP = value;
				this.SendPropertyChanged("MaSP");
				this.OnMaSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(MAX)")]
	public string TenSP
	{
		get
		{
			return this._TenSP;
		}
		set
		{
			if ((this._TenSP != value))
			{
				this.OnTenSPChanging(value);
				this.SendPropertyChanging();
				this._TenSP = value;
				this.SendPropertyChanged("TenSP");
				this.OnTenSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
	public System.Nullable<int> SoLuong
	{
		get
		{
			return this._SoLuong;
		}
		set
		{
			if ((this._SoLuong != value))
			{
				this.OnSoLuongChanging(value);
				this.SendPropertyChanging();
				this._SoLuong = value;
				this.SendPropertyChanged("SoLuong");
				this.OnSoLuongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(MAX)")]
	public string DonViTinh
	{
		get
		{
			return this._DonViTinh;
		}
		set
		{
			if ((this._DonViTinh != value))
			{
				this.OnDonViTinhChanging(value);
				this.SendPropertyChanging();
				this._DonViTinh = value;
				this.SendPropertyChanged("DonViTinh");
				this.OnDonViTinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="BigInt")]
	public System.Nullable<long> DonGia
	{
		get
		{
			return this._DonGia;
		}
		set
		{
			if ((this._DonGia != value))
			{
				this.OnDonGiaChanging(value);
				this.SendPropertyChanging();
				this._DonGia = value;
				this.SendPropertyChanged("DonGia");
				this.OnDonGiaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="VarChar(50)")]
	public string MaNCC
	{
		get
		{
			return this._MaNCC;
		}
		set
		{
			if ((this._MaNCC != value))
			{
				if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaNCCChanging(value);
				this.SendPropertyChanging();
				this._MaNCC = value;
				this.SendPropertyChanged("MaNCC");
				this.OnMaNCCChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLH", DbType="VarChar(50)")]
	public string MaLH
	{
		get
		{
			return this._MaLH;
		}
		set
		{
			if ((this._MaLH != value))
			{
				if (this._LOAIHANG.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaLHChanging(value);
				this.SendPropertyChanging();
				this._MaLH = value;
				this.SendPropertyChanged("MaLH");
				this.OnMaLHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CHITIETDATHANG", Storage="_CHITIETDATHANGs", ThisKey="MaSP", OtherKey="MaSP")]
	public EntitySet<CHITIETDATHANG> CHITIETDATHANGs
	{
		get
		{
			return this._CHITIETDATHANGs;
		}
		set
		{
			this._CHITIETDATHANGs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHANG_SANPHAM", Storage="_LOAIHANG", ThisKey="MaLH", OtherKey="MaLoai", IsForeignKey=true)]
	internal LOAIHANG LOAIHANG
	{
		get
		{
			return this._LOAIHANG.Entity;
		}
		set
		{
			LOAIHANG previousValue = this._LOAIHANG.Entity;
			if (((previousValue != value) 
						|| (this._LOAIHANG.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._LOAIHANG.Entity = null;
					previousValue.SANPHAMs.Remove(this);
				}
				this._LOAIHANG.Entity = value;
				if ((value != null))
				{
					value.SANPHAMs.Add(this);
					this._MaLH = value.MaLoai;
				}
				else
				{
					this._MaLH = default(string);
				}
				this.SendPropertyChanged("LOAIHANG");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_SANPHAM", Storage="_NHACUNGCAP", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
	internal NHACUNGCAP NHACUNGCAP
	{
		get
		{
			return this._NHACUNGCAP.Entity;
		}
		set
		{
			NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
			if (((previousValue != value) 
						|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._NHACUNGCAP.Entity = null;
					previousValue.SANPHAMs.Remove(this);
				}
				this._NHACUNGCAP.Entity = value;
				if ((value != null))
				{
					value.SANPHAMs.Add(this);
					this._MaNCC = value.MaNCC;
				}
				else
				{
					this._MaNCC = default(string);
				}
				this.SendPropertyChanged("NHACUNGCAP");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_CHITIETDATHANGs(CHITIETDATHANG entity)
	{
		this.SendPropertyChanging();
		entity.SANPHAM = this;
	}
	
	private void detach_CHITIETDATHANGs(CHITIETDATHANG entity)
	{
		this.SendPropertyChanging();
		entity.SANPHAM = null;
	}
}
#pragma warning restore 1591
